### ISSUE TITLE
Excessive console messages causes slowdown

### ISSUE THREAD

**Issue by objectchris** [libretro/mame2000-libretro#12]
eg Robotron 2084 (note: you have to select 'Content Settings' > 'Restart Content' in the retroarch GUI after you get the "Factory Settings Restored" message, else it will hang) - you'll notice that when the player spawns at the start of the game, it slows to a crawl. The reason for this is it's logging a load of error messages to the console. If you instead start with 
 ./retroarch > /dev/null
it doesn't display these messages, and the game plays flawlessly.

Hopefully there's a way of still tracking the errors, but not overloading the gameplay like it is?

**Comment by joolswills** [comment]
I'm going to just ifdef out the logging for RetroPie-Setup as it is way too verbose, but I guess the best thing would be to hook it into the RetroArch logging which has log levels and set them to INFO so the errors only show if core logging is verbose. This requires an updated libretro header and some other things I guess though.
