### ISSUE TITLE
No music in Bubble Bobble (bublbobl)

### ISSUE THREAD

**Issue by vanfanel** [libretro/mame2000-libretro#15]
There's no music in Bubble Bobble with the Mame2000 core. There is music on 0.37b5 and standalone mame4all.
Built and tested on Raspberry Pi 1 (ARM).

**Comment by vanfanel** [comment]
This game uses YM3526 for music. 
Further investigation reveals that ifdef-ed code src/sound/fmopl.cpp depending on the BUILD_YM3526 define is being built, but the YM3812UpdateOne() and FM_OPL *OPLCreate() functions are not being called.
emu_YM3812_sh_start() in src/sound/3812intf.c is responsible for calling OPL_Create(), and is not called either. 
The root of all this is in OPL_sh_start(), where the emulator choses to use emulated ym3812 or not, based on the options.use_emulated_ym3812 variable. So it can be easily enabled and, in fact, works great.
The value to options.use_emulated_ym3812 is assigned in parse_cmdline() in src/libretro/config.c, which again is never called.

**Comment by Stathman** [comment]
Hi, 
i'm using a Raspberry pi 2.

Can you please explain to me what i have to do, as plain as you can,
so i can fix the music issue in bubble bobble?

Thanks a lot.

**Comment by vanfanel** [comment]
Hi, Slathman

All you have to do is build the latest mame2000 core from the latest source revision in this repo. Music will be fixed with that version of the core.

**Comment by Stathman** [comment]
I don't have a clue how to do this,
but i will try to find it. 

Thank you for replying and of course for the fix.
