### ISSUE TITLE
OS X build errors - clang

### ISSUE THREAD

**Issue by clobber** [libretro/mame2000-libretro#3]
Trying to build iMAME for libretro:

In file included from src/memory.cpp:745:
src/memory_write.h:1147:4: warning: cast from 'unsigned char *' to 'UINT16 *'
      (aka 'unsigned short *') increases required alignment from 1 to 2
      [-Wcast-align]
  ...WRITE_WORD(&cpu_bankbase[hw2][address2 - memorywriteoffset[hw2]], word2)...
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/memory.h:248:30: note: expanded from macro 'WRITE_WORD'
#define WRITE_WORD(a,d)           (*(UINT16 *)(a) = (d))
                                    ^~~~~~~~~~~~~
src/memory.cpp:891:14: error: cast from pointer to smaller type 'int' loses
      information
                hardware = (int)MWA_BANK1 - (int)handler + 1;
                           ^~~~~~~~~~~~~~
src/memory.cpp:891:31: error: cast from pointer to smaller type 'int' loses
      information
                hardware = (int)MWA_BANK1 - (int)handler + 1;
                                            ^~~~~~~~~~~~
src/memory.cpp:926:14: error: cast from pointer to smaller type 'int' loses
      information
                hardware = (int)MWA_BANK1 - (int)handler + 1;
                           ^~~~~~~~~~~~~~
src/memory.cpp:926:31: error: cast from pointer to smaller type 'int' loses
      information
                hardware = (int)MWA_BANK1 - (int)handler + 1;
                                            ^~~~~~~~~~~~
src/memory.cpp:1006:14: error: cast from pointer to smaller type 'int' loses
      information
                hardware = (int)MRA_BANK1 - (int)handler + 1;
                           ^~~~~~~~~~~~~~
src/memory.cpp:1006:31: error: cast from pointer to smaller type 'int' loses
      information
                hardware = (int)MRA_BANK1 - (int)handler + 1;
                                            ^~~~~~~~~~~~
src/memory.cpp:1094:14: error: cast from pointer to smaller type 'int' loses
      information
                hardware = (int)MWA_BANK1 - (int)handler + 1;
                           ^~~~~~~~~~~~~~
src/memory.cpp:1094:31: error: cast from pointer to smaller type 'int' loses
      information
                hardware = (int)MWA_BANK1 - (int)handler + 1;
                                            ^~~~~~~~~~~~
48 warnings and 8 errors generated.
make: *** [obj_mame_libretro/memory.o] Error 1

**Comment by objectchris** [comment]
Not sure I fully understand the issues above, but I can compile this core in OSX 10.11.3 (el-capitan) fine using the packaged makefile + xcode 7.
````
cc -v
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
````

**Comment by twinaphex** [comment]
This issue is probably no longer relevant and can safely be closed.
