### ISSUE TITLE
mame2000-libretro performs worse than mame4all

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2000-libretro#40]
[It's held as gospel truth](https://github.com/RetroPie/RetroPie-Setup/wiki/Arcade) in the RetroPie community that mame2000-libretro performs worse than mame4all even though they are both derived from the MAME 0.37b5 codebase.

I'm creating this issue simply because it's such a ubiquitous understanding in that user group but it is not being tracked on this end. Perhaps one day someone will be curious enough to investigate the discrepancy.

**Comment by hizzlekizzle** [comment]
do you know if all games are uniformly worse-performing?

**Comment by markwkidd** [comment]
Hey @herbfargus , did you write the portion of the RetroPie MAME documentation that recommends mame4all over mame2000 because of differences in performance?

If so, are you able to describe the situations or games where mame4all is superior to mame 2000?

**Comment by HerbFargus** [comment]
@markwkidd that's primarily for pi1/pi0 which I believe is the default (or was, haven't tested in a while). In my testing mame4all standalone always ran the games better for the lower spec boards and probably would for the higher spec boards too but obviously at the disadvantage of not having the libretro features.

**Comment by markwkidd** [comment]
@HerbFargus Thanks!

The RetroPie docs do still recommend mame4all on lower spec boards if that's what you mean. When I helped rework the Arcade documentation a few months back that info was already in place so I left the recommendation as it is.

If there's still a performance difference between mame4all and mame2000, there may be something that the libretro core could benefit from adopting from mame4all since they're based on the same source.

That's not a fix I'm qualified to make but I was surprised to see no issues regarding the performance difference here on github so maybe we can at least have some starting point for an investigation. Hmm.

**Comment by dankcushions** [comment]
https://github.com/squidrpi/mame4all-pi/blob/master/readme.txt

see the version history for clues why it might be faster. i think specifically:

>   * Added DrZ80 cpu core. Enabled by default for sound to improve performance for many games.

i think this is an ASM variant for ARM. i would check the makefile to see if there aren't other ASM cpu drivers used.

>   * New graphics backend may mean some 8bit games are faster, but 16bit games maybe slower.

this is using dispmanx. you can use a dispmanx graphics driver in retroarch but it's not the same, or enabled by default in retropie.

**Comment by markwkidd** [comment]
I took a first crack at compiling in the asm versions of the drivers for arm targets: https://github.com/libretro/mame2000-libretro/pull/46

**Comment by markwkidd** [comment]
@HerbFargus now that we have the faster drivers for x68000 and drz80 as well as the ability to remap and save controller settings (as of today), I am hoping that this core is as good or better than mame4all.

If there are any other performance issues that you or other folks know about please let me know. Otherwise I will close this issue in a few days.

**Comment by dankcushions** [comment]
i'm told that mame4all-pi has a few backported drivers so it supports some extra games. but i think maybe hardly anyone uses them (they wouldn't be in the 0.37b5 romset for a start). as such, i wonder if retropie docs and script shouldn't now default to lr-mame2000 for pi 1/0, instead?

I don't have a pi1/0 to test. @markwkidd - perhaps you could create a thread on the retropie forum for some feedback from pi 1/0 users? 

PS thanks for all your work! :)

**Comment by markwkidd** [comment]
Closing this issue in favor of the more specific https://github.com/libretro/mame2000-libretro/issues/53

**Comment by Wilstorm** [comment]
>i'm told that mame4all-pi has a few backported drivers so it supports some extra games

I don't know if that's completely true. I did read that somewhere also but if you take the official DAT and the mame4all DAT I believe you can build a complete set of either. I did try it before and I believe it only shifts a few ROM files around but doesn't completely eliminate them. I am not 100% on that as it's been years.

I did spend quite a bit of time with the Zero this past weekend and would add some information to a thread. It was mainly overclocking and using mame2003. Nice board but I think it's more of a niche market.

@markwkidd I know it's not performance related but controller mapping is better in my opinion. I know it may seem minute but it you can use every button on controllers in mame4all, as well as combination mappings & <NOT> mappings. I don't know if any of them changed and there are workarounds but mame4all works perfect right out of the box and just has a more polished feel when mapping.

I like using the "silver" xbox logo button in the center for pulling up the TAB menu in mame4all, also mapping controls using the joystick for example select+up arrow. Using the joystick directionals adds many, many more input combinations. Finally <NOT> mappings which has been documented in many places and does have workarounds. 

I know you had worked on these issues several months ago and I did some testing with extensive feedback. Did you work on those issues any further? The last time I tested mame2000 I would still prefer mame4all as the input is better.

Two of the biggest Libretro features I find to be staple are mapping the D-pad to analog and of course shaders. Mame4all has simple horizontal lines through the frame which pale in comparison.

**Comment by Wilstorm** [comment]
Updated comment to reflect NOT mappings properly.

**Comment by dankcushions** [comment]
@Wilstorm mame4all-pi indeed has backported drivers added: 
https://github.com/squidrpi/mame4all-pi
> Folder names or ZIP file names are listed on "gamelist.txt" file.
Romsets have to be MAME 0.37b5 ones (July 2000).
Additionaly there are additional romsets from newer MAME versions.

but yes and mame 0.37b5 romset should work in mame2000 and mame4all-pi, just mame4all-pi will support some romsets beyond that.

**Comment by Wilstorm** [comment]
>but yes and mame 0.37b5 romset should work in mame2000 and mame4all-pi, just mame4all-pi will support some romsets beyond that.

Right I knew both are derived from 0.37b5 and using both they work fine in either. I was referring to the "additional romsets from newer versions" or extra games squid added. I might have understood it wrong all those years ago with the expectation the extra games would have been in the zip with mame4all but I never found that list or a DAT for that matter. Only squids comments. I figured it would have been in the DAT packed with Mame4all but it's not. It's the same as the official. I guess the code or squid are the only two with that list of extra games that work in mame4all which as you said probably doesn't matter but I thought I read it was games he liked or were requested for addition.
