### ISSUE TITLE
mame2000 always crashes when loading roms (via win 10 x64 RetroArch)

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2000-libretro#41]
I'm working with a fresh install of the latest nightly RetroArch in Windows 10 x64. I'm working with a core downloaded from the online updater.

MAME 2003 works as expected with the same installation.

Here is some logging that I think would be relevant: https://pastebin.com/tNbwSMvq

I tested the same MAME 0.37b5 ROM in the original standalone MAME without problems.

**Comment by Quickgold74** [comment]
same here, like the mame2010 :( in download page we need a stable section for the cores (like RA) and not only for the nightly.

**Comment by markwkidd** [comment]
@r-type do you think this is the same issue as https://github.com/libretro/mame2010-libretro/issues/34?

**Comment by r-type** [comment]
yes it's look like , i will push an PR.
https://ufile.io/a9yk0

**Comment by markwkidd** [comment]
Thank you @r-type , your fix is working here in Windows
