### ISSUE TITLE
TAB menu not mapped

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2000-libretro#48]
- Operating System: Windows 7 x64
- RA Version: 1.6.7 stable

Pressing the TAB key does not bring up the MAME menu.

This Issue started as a post in the forums: https://forums.libretro.com/t/mame-2010-0-139-or-2014-0-159-for-vita-possible/12237/11

**Comment by markwkidd** [comment]
This might be the starting place for a fix: https://github.com/libretro/mame2000-libretro/blob/355af363372f1cdd7fc44fc551a13cfcf904ad07/src/libretro/input.cpp#L173

**Comment by markwkidd** [comment]
@r-type would you consider looking at this? Now the settings will be saved to disk but for some reason it's not possible to get into the tab menu to begin with.

**Comment by r-type** [comment]
#50  should handle this
