### ISSUE TITLE
Missing core input remapping feature

### ISSUE THREAD

**Issue by bankaiprimera** [libretro/mame2000-libretro#54]
Mame2000 is missing core input remapping feature, which is accessible from the quick menu’s “controls” submenu. It lets you move the core’s buttons around on the retropad.

(Nearly) all other RetroArch cores do offer this feature and it is sorely missed in mame2000.

For example Mortal Kombat's default controls are horrible, would be awesome to be able to configure them using this feature.

**Comment by retro-wertz** [comment]
isn't mame suppose to use its own gui for these stuff so its able to have per machine/game config? that's why its there and it what im using for remappings.

even current release mame do not have remappable buttons using core's quick menu.

**Comment by bankaiprimera** [comment]
Yes, maybe you're right. But without a classic controller, you can't access the MAME menu to alter the controls (it's the R2 key). This hotkey can't be altered in RA unfortunately.. so without the controller you're screwed. A basic controller option through the RA quick menu, like in every other core, would solve this problem as well.

**Comment by retro-wertz** [comment]
this should now be do able in latest commit ....

**Comment by bankaiprimera** [comment]
I want to use it on my SNES classic. User KMFDManic down @ https://github.com/KMFDManic/NESC-SNESC-Modifications/issues/29 tried compiling it, but it didn't work unfortunately..

**Comment by hizzlekizzle** [comment]
Has he explained anywhere what he needs to do to make it compile properly? Or even what errors he's getting?

**Comment by markwkidd** [comment]
@bankaiprimera I think that KMFDManiac just needs to update to the latest version of this core. The remapping feature wasn't added yet when that discussion took place which you linked.

**Comment by hizzlekizzle** [comment]
@markwkidd I'm getting email notifications for some ongoing discussion about it ... somewhere and it seems he can't get it to compile anymore, but he doesn't say why not or how he's doing it.

**Comment by markwkidd** [comment]
@bankaiprimera do you feel OK closing this Issue now that things are working for SNES Classic?

**Comment by bankaiprimera** [comment]
Yes absolutely. @KMFDManic has resolved the issue and in his latest cores it's possible to map controls in MAME2000.
